/* tslint:disable */
/* eslint-disable */
/**
 * Reserver Api
 * Room reservation management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xhozza@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * Unique identifier of the reservation
     * @type {string}
     * @memberof Reservation
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    'roomNumber': string;
}

/**
 * RoomReservationApi - axios parameter creator
 * @export
 */
export const RoomReservationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservations: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/reservation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomReservationApi - functional programming interface
 * @export
 */
export const RoomReservationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomReservationApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReservations(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Reservation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReservations(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RoomReservationApi - factory interface
 * @export
 */
export const RoomReservationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomReservationApiFp(configuration)
    return {
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservations(options?: any): AxiosPromise<Array<Reservation>> {
            return localVarFp.getReservations(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomReservationApi - interface
 * @export
 * @interface RoomReservationApi
 */
export interface RoomReservationApiInterface {
    /**
     * Use this method to get list of all reservations
     * @summary Provides the list of current reservations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    getReservations(options?: AxiosRequestConfig): AxiosPromise<Array<Reservation>>;

}

/**
 * RoomReservationApi - object-oriented interface
 * @export
 * @class RoomReservationApi
 * @extends {BaseAPI}
 */
export class RoomReservationApi extends BaseAPI implements RoomReservationApiInterface {
    /**
     * Use this method to get list of all reservations
     * @summary Provides the list of current reservations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public getReservations(options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).getReservations(options).then((request) => request(this.axios, this.basePath));
    }
}


