/* tslint:disable */
/* eslint-disable */
/**
 * Reserver Api
 * Room and ambulance reservation management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xhozza@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Department
 */
export interface Department {
    /**
     * Unique identifier of the department
     * @type {string}
     * @memberof Department
     */
    'id': string;
    /**
     * Name of the hospital department
     * @type {string}
     * @memberof Department
     */
    'name': string;
    /**
     * Description of the department
     * @type {string}
     * @memberof Department
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Doctor
 */
export interface Doctor {
    /**
     * Unique identifier of the department
     * @type {string}
     * @memberof Doctor
     */
    'id': string;
    /**
     * Name of the hospital department
     * @type {string}
     * @memberof Doctor
     */
    'name': string;
    /**
     * ID of their department
     * @type {string}
     * @memberof Doctor
     */
    'department': string;
}
/**
 * 
 * @export
 * @interface Room
 */
export interface Room {
    /**
     * Unique identifier of the room
     * @type {string}
     * @memberof Room
     */
    'id': string;
    /**
     * Room number
     * @type {string}
     * @memberof Room
     */
    'roomNumber': string;
}
/**
 * 
 * @export
 * @interface RoomReservation
 */
export interface RoomReservation {
    /**
     * Unique identifier of the reservation
     * @type {string}
     * @memberof RoomReservation
     */
    'id': string;
    /**
     * Room ID
     * @type {string}
     * @memberof RoomReservation
     */
    'room': string;
    /**
     * ID of the department
     * @type {string}
     * @memberof RoomReservation
     */
    'department': string;
    /**
     * ID of the doctor
     * @type {string}
     * @memberof RoomReservation
     */
    'doctor': string;
}

/**
 * DepartmentsApi - axios parameter creator
 * @export
 */
export const DepartmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to get list of all departments
         * @summary Provide the list of all departments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDepartments: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/departments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to get list of all doctors with their department
         * @summary Provide list of all doctors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDoctors: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/doctors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DepartmentsApi - functional programming interface
 * @export
 */
export const DepartmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DepartmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to get list of all departments
         * @summary Provide the list of all departments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDepartments(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Department>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDepartments(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to get list of all doctors with their department
         * @summary Provide list of all doctors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDoctors(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Doctor>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDoctors(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DepartmentsApi - factory interface
 * @export
 */
export const DepartmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DepartmentsApiFp(configuration)
    return {
        /**
         * Use this method to get list of all departments
         * @summary Provide the list of all departments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDepartments(options?: any): AxiosPromise<Array<Department>> {
            return localVarFp.getDepartments(options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to get list of all doctors with their department
         * @summary Provide list of all doctors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDoctors(options?: any): AxiosPromise<Array<Doctor>> {
            return localVarFp.getDoctors(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DepartmentsApi - interface
 * @export
 * @interface DepartmentsApi
 */
export interface DepartmentsApiInterface {
    /**
     * Use this method to get list of all departments
     * @summary Provide the list of all departments
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    getDepartments(options?: AxiosRequestConfig): AxiosPromise<Array<Department>>;

    /**
     * Use this method to get list of all doctors with their department
     * @summary Provide list of all doctors
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    getDoctors(options?: AxiosRequestConfig): AxiosPromise<Array<Doctor>>;

}

/**
 * DepartmentsApi - object-oriented interface
 * @export
 * @class DepartmentsApi
 * @extends {BaseAPI}
 */
export class DepartmentsApi extends BaseAPI implements DepartmentsApiInterface {
    /**
     * Use this method to get list of all departments
     * @summary Provide the list of all departments
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApi
     */
    public getDepartments(options?: AxiosRequestConfig) {
        return DepartmentsApiFp(this.configuration).getDepartments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to get list of all doctors with their department
     * @summary Provide list of all doctors
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApi
     */
    public getDoctors(options?: AxiosRequestConfig) {
        return DepartmentsApiFp(this.configuration).getDoctors(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RoomReservationApi - axios parameter creator
 * @export
 */
export const RoomReservationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to create new reservation
         * @summary Create new reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservation: async (roomReservation: RoomReservation, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomReservation' is not null or undefined
            assertParamExists('createReservation', 'roomReservation', roomReservation)
            const localVarPath = `/reservation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomReservation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to delete reservation
         * @summary Delete reservation
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservation: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteReservation', 'id', id)
            const localVarPath = `/reservation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to get reservation by id
         * @summary Provides the reservation by id
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getReservationById', 'id', id)
            const localVarPath = `/reservation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservations: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/reservation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to get list of all rooms
         * @summary Provides the list of all rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRooms: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/rooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to update reservation
         * @summary Update reservation
         * @param {string} id ID of the reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateReservation: async (id: string, roomReservation: RoomReservation, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateReservation', 'id', id)
            // verify required parameter 'roomReservation' is not null or undefined
            assertParamExists('updateReservation', 'roomReservation', roomReservation)
            const localVarPath = `/reservation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomReservation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomReservationApi - functional programming interface
 * @export
 */
export const RoomReservationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomReservationApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to create new reservation
         * @summary Create new reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createReservation(roomReservation: RoomReservation, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoomReservation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createReservation(roomReservation, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to delete reservation
         * @summary Delete reservation
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteReservation(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteReservation(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to get reservation by id
         * @summary Provides the reservation by id
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReservationById(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoomReservation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReservationById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReservations(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RoomReservation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReservations(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to get list of all rooms
         * @summary Provides the list of all rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRooms(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Room>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRooms(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to update reservation
         * @summary Update reservation
         * @param {string} id ID of the reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateReservation(id: string, roomReservation: RoomReservation, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoomReservation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateReservation(id, roomReservation, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RoomReservationApi - factory interface
 * @export
 */
export const RoomReservationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomReservationApiFp(configuration)
    return {
        /**
         * Use this method to create new reservation
         * @summary Create new reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservation(roomReservation: RoomReservation, options?: any): AxiosPromise<RoomReservation> {
            return localVarFp.createReservation(roomReservation, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to delete reservation
         * @summary Delete reservation
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservation(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteReservation(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to get reservation by id
         * @summary Provides the reservation by id
         * @param {string} id ID of the reservation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationById(id: string, options?: any): AxiosPromise<RoomReservation> {
            return localVarFp.getReservationById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to get list of all reservations
         * @summary Provides the list of current reservations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservations(options?: any): AxiosPromise<Array<RoomReservation>> {
            return localVarFp.getReservations(options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to get list of all rooms
         * @summary Provides the list of all rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRooms(options?: any): AxiosPromise<Array<Room>> {
            return localVarFp.getRooms(options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to update reservation
         * @summary Update reservation
         * @param {string} id ID of the reservation
         * @param {RoomReservation} roomReservation 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateReservation(id: string, roomReservation: RoomReservation, options?: any): AxiosPromise<RoomReservation> {
            return localVarFp.updateReservation(id, roomReservation, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomReservationApi - interface
 * @export
 * @interface RoomReservationApi
 */
export interface RoomReservationApiInterface {
    /**
     * Use this method to create new reservation
     * @summary Create new reservation
     * @param {RoomReservation} roomReservation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    createReservation(roomReservation: RoomReservation, options?: AxiosRequestConfig): AxiosPromise<RoomReservation>;

    /**
     * Use this method to delete reservation
     * @summary Delete reservation
     * @param {string} id ID of the reservation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    deleteReservation(id: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * Use this method to get reservation by id
     * @summary Provides the reservation by id
     * @param {string} id ID of the reservation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    getReservationById(id: string, options?: AxiosRequestConfig): AxiosPromise<RoomReservation>;

    /**
     * Use this method to get list of all reservations
     * @summary Provides the list of current reservations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    getReservations(options?: AxiosRequestConfig): AxiosPromise<Array<RoomReservation>>;

    /**
     * Use this method to get list of all rooms
     * @summary Provides the list of all rooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    getRooms(options?: AxiosRequestConfig): AxiosPromise<Array<Room>>;

    /**
     * Use this method to update reservation
     * @summary Update reservation
     * @param {string} id ID of the reservation
     * @param {RoomReservation} roomReservation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApiInterface
     */
    updateReservation(id: string, roomReservation: RoomReservation, options?: AxiosRequestConfig): AxiosPromise<RoomReservation>;

}

/**
 * RoomReservationApi - object-oriented interface
 * @export
 * @class RoomReservationApi
 * @extends {BaseAPI}
 */
export class RoomReservationApi extends BaseAPI implements RoomReservationApiInterface {
    /**
     * Use this method to create new reservation
     * @summary Create new reservation
     * @param {RoomReservation} roomReservation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public createReservation(roomReservation: RoomReservation, options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).createReservation(roomReservation, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to delete reservation
     * @summary Delete reservation
     * @param {string} id ID of the reservation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public deleteReservation(id: string, options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).deleteReservation(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to get reservation by id
     * @summary Provides the reservation by id
     * @param {string} id ID of the reservation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public getReservationById(id: string, options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).getReservationById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to get list of all reservations
     * @summary Provides the list of current reservations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public getReservations(options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).getReservations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to get list of all rooms
     * @summary Provides the list of all rooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public getRooms(options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).getRooms(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to update reservation
     * @summary Update reservation
     * @param {string} id ID of the reservation
     * @param {RoomReservation} roomReservation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomReservationApi
     */
    public updateReservation(id: string, roomReservation: RoomReservation, options?: AxiosRequestConfig) {
        return RoomReservationApiFp(this.configuration).updateReservation(id, roomReservation, options).then((request) => request(this.axios, this.basePath));
    }
}


