/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReserverApp {
        "apiBase": string;
        "basePath": string;
    }
    interface ReserverExaminationEditor {
        "apiBase": string;
        "entityId": string;
    }
    interface ReserverExaminationList {
        "apiBase": string;
    }
    interface ReserverHome {
    }
    interface ReserverReservationEditor {
        "apiBase": string;
        "entityId": string;
    }
    interface ReserverRoomList {
        "apiBase": string;
    }
}
export interface ReserverExaminationEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReserverExaminationEditorElement;
}
export interface ReserverExaminationListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReserverExaminationListElement;
}
export interface ReserverHomeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReserverHomeElement;
}
export interface ReserverReservationEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReserverReservationEditorElement;
}
export interface ReserverRoomListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReserverRoomListElement;
}
declare global {
    interface HTMLReserverAppElement extends Components.ReserverApp, HTMLStencilElement {
    }
    var HTMLReserverAppElement: {
        prototype: HTMLReserverAppElement;
        new (): HTMLReserverAppElement;
    };
    interface HTMLReserverExaminationEditorElementEventMap {
        "navigate": string;
    }
    interface HTMLReserverExaminationEditorElement extends Components.ReserverExaminationEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReserverExaminationEditorElementEventMap>(type: K, listener: (this: HTMLReserverExaminationEditorElement, ev: ReserverExaminationEditorCustomEvent<HTMLReserverExaminationEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReserverExaminationEditorElementEventMap>(type: K, listener: (this: HTMLReserverExaminationEditorElement, ev: ReserverExaminationEditorCustomEvent<HTMLReserverExaminationEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReserverExaminationEditorElement: {
        prototype: HTMLReserverExaminationEditorElement;
        new (): HTMLReserverExaminationEditorElement;
    };
    interface HTMLReserverExaminationListElementEventMap {
        "navigate": string;
    }
    interface HTMLReserverExaminationListElement extends Components.ReserverExaminationList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReserverExaminationListElementEventMap>(type: K, listener: (this: HTMLReserverExaminationListElement, ev: ReserverExaminationListCustomEvent<HTMLReserverExaminationListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReserverExaminationListElementEventMap>(type: K, listener: (this: HTMLReserverExaminationListElement, ev: ReserverExaminationListCustomEvent<HTMLReserverExaminationListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReserverExaminationListElement: {
        prototype: HTMLReserverExaminationListElement;
        new (): HTMLReserverExaminationListElement;
    };
    interface HTMLReserverHomeElementEventMap {
        "navigate": string;
    }
    interface HTMLReserverHomeElement extends Components.ReserverHome, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReserverHomeElementEventMap>(type: K, listener: (this: HTMLReserverHomeElement, ev: ReserverHomeCustomEvent<HTMLReserverHomeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReserverHomeElementEventMap>(type: K, listener: (this: HTMLReserverHomeElement, ev: ReserverHomeCustomEvent<HTMLReserverHomeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReserverHomeElement: {
        prototype: HTMLReserverHomeElement;
        new (): HTMLReserverHomeElement;
    };
    interface HTMLReserverReservationEditorElementEventMap {
        "navigate": string;
    }
    interface HTMLReserverReservationEditorElement extends Components.ReserverReservationEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReserverReservationEditorElementEventMap>(type: K, listener: (this: HTMLReserverReservationEditorElement, ev: ReserverReservationEditorCustomEvent<HTMLReserverReservationEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReserverReservationEditorElementEventMap>(type: K, listener: (this: HTMLReserverReservationEditorElement, ev: ReserverReservationEditorCustomEvent<HTMLReserverReservationEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReserverReservationEditorElement: {
        prototype: HTMLReserverReservationEditorElement;
        new (): HTMLReserverReservationEditorElement;
    };
    interface HTMLReserverRoomListElementEventMap {
        "navigate": string;
    }
    interface HTMLReserverRoomListElement extends Components.ReserverRoomList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReserverRoomListElementEventMap>(type: K, listener: (this: HTMLReserverRoomListElement, ev: ReserverRoomListCustomEvent<HTMLReserverRoomListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReserverRoomListElementEventMap>(type: K, listener: (this: HTMLReserverRoomListElement, ev: ReserverRoomListCustomEvent<HTMLReserverRoomListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReserverRoomListElement: {
        prototype: HTMLReserverRoomListElement;
        new (): HTMLReserverRoomListElement;
    };
    interface HTMLElementTagNameMap {
        "reserver-app": HTMLReserverAppElement;
        "reserver-examination-editor": HTMLReserverExaminationEditorElement;
        "reserver-examination-list": HTMLReserverExaminationListElement;
        "reserver-home": HTMLReserverHomeElement;
        "reserver-reservation-editor": HTMLReserverReservationEditorElement;
        "reserver-room-list": HTMLReserverRoomListElement;
    }
}
declare namespace LocalJSX {
    interface ReserverApp {
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface ReserverExaminationEditor {
        "apiBase"?: string;
        "entityId"?: string;
        "onNavigate"?: (event: ReserverExaminationEditorCustomEvent<string>) => void;
    }
    interface ReserverExaminationList {
        "apiBase"?: string;
        "onNavigate"?: (event: ReserverExaminationListCustomEvent<string>) => void;
    }
    interface ReserverHome {
        "onNavigate"?: (event: ReserverHomeCustomEvent<string>) => void;
    }
    interface ReserverReservationEditor {
        "apiBase"?: string;
        "entityId"?: string;
        "onNavigate"?: (event: ReserverReservationEditorCustomEvent<string>) => void;
    }
    interface ReserverRoomList {
        "apiBase"?: string;
        "onNavigate"?: (event: ReserverRoomListCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "reserver-app": ReserverApp;
        "reserver-examination-editor": ReserverExaminationEditor;
        "reserver-examination-list": ReserverExaminationList;
        "reserver-home": ReserverHome;
        "reserver-reservation-editor": ReserverReservationEditor;
        "reserver-room-list": ReserverRoomList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reserver-app": LocalJSX.ReserverApp & JSXBase.HTMLAttributes<HTMLReserverAppElement>;
            "reserver-examination-editor": LocalJSX.ReserverExaminationEditor & JSXBase.HTMLAttributes<HTMLReserverExaminationEditorElement>;
            "reserver-examination-list": LocalJSX.ReserverExaminationList & JSXBase.HTMLAttributes<HTMLReserverExaminationListElement>;
            "reserver-home": LocalJSX.ReserverHome & JSXBase.HTMLAttributes<HTMLReserverHomeElement>;
            "reserver-reservation-editor": LocalJSX.ReserverReservationEditor & JSXBase.HTMLAttributes<HTMLReserverReservationEditorElement>;
            "reserver-room-list": LocalJSX.ReserverRoomList & JSXBase.HTMLAttributes<HTMLReserverRoomListElement>;
        }
    }
}
